### ISSUE TITLE
Can't get Wysihat to work in Rails (displays but won't save)

### ISSUE THREAD

**Issue by axoline** [basecamp/wysihat#16]
Hi guys,

This has been driving me nuts for a while and my lack of javascript knowledge isn't helping me I'm sure.

I'm able to get wysihat to function correctly (I copied most of the code from the example simple.html to tie with my textarea id of 'post-description' and it works great). However, when I go to save the entry, rails kicks back a validation error saying that the description is empty.

So somehow wysihat's div isn't "copying" the text entered into the actual 'post-description' textarea field. I've looked into the documentation and I MAY need to add some extra javascript, but I have no clue where to begin.

Before others suggest wysihat-engine, I tried it and it's good but it's overkill for what I need. All I need is the bold, underline, and unordered stylings. No attachments, links, etc.

Any help is GREATLY appreciated (this is the second to last thing I need before I launch my personal project!)

Thanks!
-Tony

**Comment by Senne** [comment]
This helped me a lot. Don't know why this isn't built in by default...?
