### ISSUE TITLE
Firefox arrow keys don't work when wysihat is on the page

### ISSUE THREAD

**Issue by trevorturk** [basecamp/wysihat#29]
In browsers, you can usually use the up/down arrow keys (or the spacebar) to scroll the page if it's too long to fit everything in the visible window. In Firefox, when wysihat is on the page, those keys don't work. 

You can see this in action by opening "examples/simple.html" in Firefox and Safari at the same time. If you make the window very small in Safari and press the up/down arrow keys, you'll see it scroll the window. The same doesn't happen in Firefox, even though it normally does (if you visit, say http://github.com, you can see it working.)

**Comment by packagethief** [comment]
I think this is a Firefox bug:

https://bugzilla.mozilla.org/show_bug.cgi?id=481626
https://bugzilla.mozilla.org/show_bug.cgi?id=601180

**Comment by trevorturk** [comment]
Word up. Sorry, I should have searched for that. Closing!
